# Generated by Django 4.2.7 on 2023-12-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
        ('catagories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagorymodel',
            name='task',
            field=models.ManyToManyField(default=None, to='task.taskmodel'),
        ),
    ]
