# Generated by Django 4.2.7 on 2023-12-27 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catagories', '0002_alter_catagorymodel_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catagorymodel',
            name='task',
        ),
        migrations.AddField(
            model_name='catagorymodel',
            name='task',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
