# Generated by Django 4.2.7 on 2023-12-27 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catagories', '0003_remove_catagorymodel_task_catagorymodel_task'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='task',
            field=models.ManyToManyField(default=None, to='catagories.catagorymodel'),
        ),
    ]
